name: Deploy Frontend to Cloud Storage

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: food-calorie-project-492710
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Deploy frontend to Cloud Storage
        run: |
          gsutil -m cp -r frontend/* gs://nutricloud-frontend-app/